apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/Venkatramshesh/gitops-argo.git'
    targetRevision: main
    path: sample-flask-helm-app/helm-chart      # <-- folder that contains Chart.yaml

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true