name: CI/CD Pipeline with GitOps (SSH)

on:
  push:
    branches: [main]

jobs:
  build-tag-push-update:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/flask-app

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Set image tag as commit SHA
      run: echo "IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

    - name: Build and push Docker image
      run: |
        docker build -t $IMAGE_NAME:${{ env.IMAGE_TAG }} ./sample-flask-helm-app
        docker push $IMAGE_NAME:${{ env.IMAGE_TAG }}

    - name: Update values.yaml with new image tag
      run: |
        sed -i "s|tag:.*|tag: \"${{ env.IMAGE_TAG }}\"|g" sample-flask-helm-app/helm-chart/values.yaml

    - name: Set up SSH for pushing to GitHub
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GH_TOKEN }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Push updated values.yaml back to repo
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git remote set-url origin git@github.com:Venkatramshesh/gitops-argo.git
        git add sample-flask-helm-app/helm-chart/values.yaml
        git commit -m "Update image tag to $IMAGE_TAG"
        git push origin main